### ISSUE TITLE
default.yaml doesn't result in passing defaults to the specified verbs

### ISSUE THREAD

**Issue by mikaelarguedas** [colcon/colcon-defaults#4]
It looks like the `defaults.yaml` file is processed before the parser has been populated. So the default values generate warnings and are not passed ot the relevant verb.

### How to reproduce
Following the documentation:
- create a defaults.yaml in COLCON_HOME with the following content:
```
{
    "build": {
        "symlink-install": true
    }
}
```
- run a build command:
```
colcon build --packages-select rcutils
```

### Expected behavior

Default defined in defaults.yaml are recognized and passed to the build verb

### Actual behavior

Prints: `WARNING:colcon.colcon_defaults.argument_parser.defaults:Unknown configuration option 'build.symlink-install'`
And the default value is not passed to the verb so no symlink install is performed

**Comment by dirk-thomas** [comment]
I think the feature does work in general. But atm it still uses the destination name rather than the name of the option (see https://github.com/colcon/colcon-defaults/blob/dd89881434ab7a44aae49163ad3266846d4f41a0/colcon_defaults/argument_parser/defaults.py#L60). So if you could try using `symlink_install` instead that would confirm that the processing does work fine.

The code should be updated to use the information available from colcon/colcon-core#24 and match the expected behavior of using the names from the command line interface.
